### ISSUE TITLE
Blocky

### ISSUE THREAD

**Issue by ldnora** [AtaraxiaSjel/nixos-config#3]
Hi!

You install the blocky at the file machines/NixOS-VPS/services/dns.nix. What's the tutorial to install it?

**Comment by AtaraxiaSjel** [comment]
Hi!

I'd be happy to help, but what do you mean? You don't understand where to put services.blocky in your configuration.nix (or flake) or how to configure blocky properly?

**Comment by ldnora** [comment]
Oh, i'm sorry. 

I underestand how to put it, and i think i've set it up correctly, based in the [doc](https://nixos.wiki/wiki/Blocky).

I only create the file  [blocky.nix](https://github.com/Leandro-Dalla-Nora/nixos-config/blob/main/modules/nixos/blocky.nix) and added to the [flake.nix](https://github.com/Leandro-Dalla-Nora/nixos-config/blob/main/flake.nix) (ln 46). 

I have difficult getting the service to work. I build the system, and it don't block the blacklist.

**Comment by AtaraxiaSjel** [comment]
Your configuration seems fine. Maybe you don't configured blocky as your system dns and your system using something else as dns? Check it with `dig`:
```bash
dig google.com
```
In the bottom of output you would see something like this:
```
;; SERVER: 100.100.100.100#53(100.100.100.100) (UDP)
```
If your blocky service is in your machine you should see 127.0.0.1 as server ip address.

**Comment by ldnora** [comment]
I configurated the `1.1.1.1` as my dns server, at the file `/etc/resolv.conf`.

With the command `ip addr`, i find this ip. 

Then i need configure the `/etc/resolv.conf` to use the blocky ip?

**Comment by AtaraxiaSjel** [comment]
Yes, of course. But instead of manually change `resolv.conf` it would better to use nixos option. Try set this in your flake:
```nix
networking.resolvconf.enable = true;
networking.resolvconf.useLocalResolver = true;
```
As you can see [here](https://github.com/NixOS/nixpkgs/blob/f8e2ebd66d097614d51a56a755450d4ae1632df1/nixos/modules/config/resolvconf.nix#L28), NixOS would set `name_servers` to 127.0.0.1.

Please, send me an update if this would help you or not.

**Comment by ldnora** [comment]
Wow, thank's bro! It work soo good for me.

Fortunately, i have a new problem. Some famous dns don't open. My blacklist is very strong hehehhe. 

Other question. For the most software that are used to block dns, proxy, etc. that run in local machine, is necessary to configurate the ip route?

**Comment by AtaraxiaSjel** [comment]
Glad it work for you!

For the other question - if I am be honest, I don't quite sure what you are asking about. What do you mean by that software?

I am not a "network" guy, but I don't think you would need change something else for your dns working. Some programs can use hardcoded dns addresses and they can bypass your blocky, but it's not a common thing. Most apps should work as is.

Also, for your information, you configure only your NixOS machine to use blocky, other devices in your home network would not use it, for example your phone or another PC.

**Comment by ldnora** [comment]
Sorry for not being specific.

For example, you decied to use a proxy to any reason. You use it in local machine, like you said, other devices wouldn't use it. To realy apply this chances, is necessary configurate the network, like the blocky?

**Comment by AtaraxiaSjel** [comment]
Sorry for the late reply!

> really apply this chances
What changes are you mean? You want to use your blocky with other devices?
